# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-strategy-nvim 'session'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
set -g @plugin 'christoomey/vim-tmux-navigator'

# reload config
bind r source-file ~/.config/tmux/tmux.conf

# second prefix
set -g prefix2 C-a
bind C-a send-prefix -2

# 256-color support
set -g default-terminal 'tmux-256color'

# zero-out escape time delay
set -g escape-time 0

# increase scrollback
set -g history-limit 1000000

# stay in tmux when closing session
set -g detach-on-destroy off

set -g set-clipboard on

set -g mouse on

set -g mode-keys vi

# vi copy-mode bindings
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle

# split in current path
bind s split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"

# window cycling
bind H previous-window
bind L next-window

set -g base-index 1
set -g pane-base-index 1

# renumber when window is closed
set -g renumber-windows on

# keep window names after renaming
set-option -g allow-rename off

set -g status-position top

# catppuccin theme
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_current_text " #W#{?window_zoomed_flag,(),}"
# load catppuccin (must precede status line config)
run "$HOME/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux"
# status line
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"

# init tpm (keep at bottom)
run "$HOME/.config/tmux/plugins/tpm/tpm"
