"$schema" = "https://starship.rs/config-schema.json"

palette = "catppuccin_mocha"

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$git_metrics\
$cmd_duration\
$fill\
$all\
$time\
$line_break\
$character"""

[aws]
symbol = " "

[buf]
symbol = " "

[bun]
format = "[$symbol($version )]($style)"
symbol = " "

[c]
format = "[$symbol($version(-$name) )]($style)"
symbol = " "

[cmd_duration]
show_milliseconds = true
style = "bold subtext0"

[cpp]
format = "[$symbol($version(-$name) )]($style)"
symbol = " "

[cmake]
format = "[$symbol($version )]($style)"
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[deno]
format = "[$symbol($version )]($style)"
symbol = " "

[directory]
truncation_length = 3
truncate_to_repo = true
truncation_symbol = "…/"
style = "bold blue"
read_only = " 󰌾"

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fill]
symbol = " "

[fortran]
symbol = " "

[fossil_branch]
symbol = " "

[gcloud]
format = "([$symbol$account](white))([@$project](blue)) "
symbol = "󱇶 "

[git_branch]
symbol = " "
style = "bold mauve"

[git_commit]
tag_symbol = '  '

[git_metrics]
disabled = false

[golang]
format = "[$symbol($version )]($style)"
symbol = " "

[gradle]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
format = "[$symbol($version )]($style)"
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
format = "[$symbol($version )]($style)"
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
format = "[$symbol($version )]($style)"
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
AOSC = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Elementary = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Ios = "󰀷 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
Zorin = " "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[pixi]
symbol = "󰏗 "

[python]
format = "[${symbol}${pyenv_prefix}(${version} )(\\($virtualenv\\) )]($style)"
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
format = "[$symbol($version )]($style)"
symbol = " "

[rust]
format = "[$symbol($version )]($style)"
symbol = "󱘗 "

[scala]
symbol = " "

[status]
symbol = " "

[swift]
symbol = " "

[time]
format = "[\\[$time\\]]($style)"
style = "subtext0"
disabled = false

[xmake]
symbol = " "

[zig]
symbol = " "

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
