[settings]
minimum_release_age = "24h"
python.uv_venv_auto = "source"

[env]
UV_PYTHON_PREFERENCE = "only-system"

[tools]
node = "latest"
pnpm = "latest"
bun = "latest"
java = "lts"
python = "latest"
uv = "latest"

"npm:firebase-tools" = "latest"
"npm:@googleworkspace/cli" = "latest"
"npm:@mwp13/pm" = "latest"
turso = "latest"
opencode = "latest"
